// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTlIlPBsloI0wZNTiVo-LNGfzhAju4KWM',
    appId: '1:173687049522:web:e6a293eb892c4460b25b2b',
    messagingSenderId: '173687049522',
    projectId: 'mindmate-917e3',
    authDomain: 'mindmate-917e3.firebaseapp.com',
    storageBucket: 'mindmate-917e3.firebasestorage.app',
    measurementId: 'G-CZ5T5BZM0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGVk8ABmD6_EMivcmL4mbslV7XIR4ylwo',
    appId: '1:173687049522:android:c1c91d62c0a7647eb25b2b',
    messagingSenderId: '173687049522',
    projectId: 'mindmate-917e3',
    storageBucket: 'mindmate-917e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwN761DuKDjXnBmYsEBiUN139c_AqyVKE',
    appId: '1:173687049522:ios:b6af31b942cfe300b25b2b',
    messagingSenderId: '173687049522',
    projectId: 'mindmate-917e3',
    storageBucket: 'mindmate-917e3.firebasestorage.app',
    iosClientId: '173687049522-kch36q3i1n1laguvp88v8f3an2junn68.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwN761DuKDjXnBmYsEBiUN139c_AqyVKE',
    appId: '1:173687049522:ios:b6af31b942cfe300b25b2b',
    messagingSenderId: '173687049522',
    projectId: 'mindmate-917e3',
    storageBucket: 'mindmate-917e3.firebasestorage.app',
    iosClientId: '173687049522-kch36q3i1n1laguvp88v8f3an2junn68.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTlIlPBsloI0wZNTiVo-LNGfzhAju4KWM',
    appId: '1:173687049522:web:ce41ddabaee29644b25b2b',
    messagingSenderId: '173687049522',
    projectId: 'mindmate-917e3',
    authDomain: 'mindmate-917e3.firebaseapp.com',
    storageBucket: 'mindmate-917e3.firebasestorage.app',
    measurementId: 'G-TG6RTHNEVW',
  );
}
